rootUrl: http://localhost:9001/
gridUrl: http://ondemand.saucelabs.com/wd/hub
windowSize: 1024x768
system:
  plugins:
    sauce:
      username:
      accessKey:
browsers:
  chrome:
    desiredCapabilities:
      browserName: chrome
      version: 54.0
      platform: MacOs 10.12
      name: gemini visual regression tests
