rootUrl: http://localhost:9001/
gridUrl: http://ondemand.saucelabs.com/wd/hub
windowSize: 1024x768
system:
  plugins:
    sauce:
      username:
      accessKey:
browsers:
  # chrome:
  #   desiredCapabilities:
  #     browserName: 'chrome'
  #     version: '54.0'
  #     platform: 'macOs 10.12'
  #     name: 'gemini visual regression tests chrome'
  firefox:
    desiredCapabilities:
      browserName: 'firefox'
      version: '50.0'
      platform: 'macOs 10.12'
      name: gemini visual regression tests firefox
  # safari:
  #   desiredCapabilities:
  #     browserName: 'safari'
  #     version: '10'
  #     platform: 'macOs 10.12'
  #     name: 'gemini visual regression tests safari'
  # edge:
  #   desiredCapabilities:
  #     browserName: 'MicrosoftEdge'
  #     version: '14.14393'
  #     platform: 'Windows 10'
  #     name: 'gemini visual regression tests edge'
